modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/YukkuriC/CuriosMediaHolder/issues"
license = "MIT"

[[mods]]
modId = "curios_media_holder"
version = "${version}"
displayName = "CuriosMediaHolder"
authors = "YukkuriC"
description = '''
An addon of HexCasting, making media holder items able to go inside Curios slots.
'''
logoFile = "logo.png"
updateJSONURL = "https://api.modrinth.com/updates/A7vBsE7N/forge_updates.json"
displayURL = "https://modrinth.com/mod/curios-media-holder"

[[dependencies.curios_media_holder]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.curios_media_holder]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.1.1)"
ordering = "NONE"
side = "BOTH"

[[dependencies.curios_media_holder]]
modId = "hexcasting"
mandatory = true
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"
